import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "../app/ClientProvider"
import { Provider } from "react-redux";
import store from "./store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      
    <html lang="en">
      <ClientProvider>
      <body className={inter.className}>{children}</body>
      </ClientProvider>
    </html>
      
  );
}
